modLoader="javafml"
loaderVersion="[31,)"
[[mods]] 
modId="moturtles"
version="1.0"
displayName="Mo' Turtles Mod"
authors="TurtyWurty"
description='''
A minecraft mod that adds more turtles.
'''

[[dependencies.moturtles]] 
    modId="forge"
    mandatory=true 
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moturtles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
